### PR TITLE
Clean up Makefiles and build with binary name

### PR DESCRIPTION
**Pull request by sigv**
Although a default name of `main` works, it can be very beneficial to build executables with their final names wherever possible. An example for where this has an impact is if during the build stages automatic manpage generation were to be done on the executable - some tools utilize the executable name for context.

This does however mean anyone working with the local executables without installing them would have to adjust their tooling in use to accommodate this rename (s/main/rvrrpd/).

### CODE REVIEW

**Comment by sigv** [comment]
`Makefile` changes apply to `0.2.0-dev` branch.
`src/bin/*.rs` rename might not be clean - but really it's just `mv src/bin/{main,rvrrpd}.rs` under the hood here.

**Review by e3prom — CHANGES_REQUESTED** [review]
Thanks for pointing that out. I think we can safely rename those files, it won't break the development environment, so it's all good.

However, I've just figured out that the calls to `mkdir -p` have quotation `"` characters around the argument/directory path, it returns an error and therefore the Makefile's target fails. Could you fix that for me? It was my error, but we can correct it in your pull request 😅

**Comment by sigv** [comment]
Just realized, the docs output is still out of date, as there are other changes that have taken place. Will patch that up in a sec.

**Comment by e3prom** [comment]
Could you provide me access to your fork as a collaborator ? I've changed (I should say fixed) the logic of the Makefiles. We can then get all changes back in the pull request and merge into `master`, then `0.2.0-dev`.

**Comment by sigv** [comment]
You should be able to add new commits to the `makefile-binary` branch now.

**Comment by sigv** [comment]
If we are expanding this to cover more Makefile fixes, I will roll #6 into it as well. Originally split that off to keep each PR as small as possible, but as this is growing - that just makes sense to include here too.

**Comment by e3prom** [comment]
I've just pushed my changes. Let me know what you think about them: I've used basic `if` conditional statements to check if the directories exists and call `mkdir -p` if necessary. It looks simpler/dumber, but that's probably better at the end, and less prone to issues.

**Comment by sigv** [comment]
Might be shell-specific then, that it was working for me. In any case, it does look reasonable to me! 👍🏻

**Comment by sigv** [comment]
Just realized the `make -C` change is not being shown in the docs update. 😞

**Comment by e3prom** [comment]
Doc updated! Thanks again for the contribution. If you've important updates in the future, please make a branch from `0.2.0-dev` and make the pull request from it. I can't unfortunately affect the PR to another branch, it looks like the feature is no longer supported by github.

**Comment by sigv** [comment]
I am preparing to evaluate the rVRRPd package in our infrastructure and these changes to the build process (Makefiles) are all inclined towards making the packaging process nicer. When I get to manpages, I can of course push those as targeted towards the `v0.2` branch, however these initial Makefile changes here seem like nice improvements to both branches in my opinion.

On a similar note, are no more maintenance" `v0.1` releases expected?

**Comment by sigv** [comment]
Additionally, I can prep a separate PR for `v0.2` branch if you want to.
Or would you rather manually handle the merge on your side?

**Comment by e3prom** [comment]
Yes, I will merge this PR to both branches in a few hours.

Man pages and distribution packages would be great additions to this project, for sure! It also a good opportunity to make a new release soon, based on the `0.2.0-dev` branch, where a lot of code cleanup has already been made. I'm not planning to add new features soon though, but if there is bugs or major issues, I will fix them as soon as possible and make a release here.

**Pull request merged**
